cmake_minimum_required(VERSION 3.19)

if(NOT PORTABLE_SOURCE_DIR OR NOT PORTABLE_DIST_DIR)
    message(FATAL_ERROR "PORTABLE_SOURCE_DIR and PORTABLE_DIST_DIR are required")
endif()

if(PORTABLE_CORE_SOURCE_DIR)
    set(core "${PORTABLE_CORE_SOURCE_DIR}")
else()
    file(READ "${PORTABLE_SOURCE_DIR}/versions.lock.json" core_lock)
    string(JSON core_patch_count ERROR_VARIABLE core_patch_error LENGTH "${core_lock}" core patches)
    if(NOT core_patch_error AND core_patch_count GREATER 0)
        set(core "${PORTABLE_SOURCE_DIR}/.module-cache/prepared-core")
    else()
        set(core "${PORTABLE_SOURCE_DIR}/azerothcore-wotlk")
    endif()
endif()
if(NOT IS_DIRECTORY "${core}/data/sql")
    message(FATAL_ERROR "AzerothCore SQL is missing: initialize the pinned core submodule")
endif()
file(MAKE_DIRECTORY "${PORTABLE_DIST_DIR}/src/data" "${PORTABLE_DIST_DIR}/configs/modules"
    "${PORTABLE_DIST_DIR}/licenses" "${PORTABLE_DIST_DIR}/patches")
# These are generated source exports, not the live MySQL data or configuration.
# Replace them so deleted migrations and SQL from removed modules cannot survive.
file(REMOVE_RECURSE "${PORTABLE_DIST_DIR}/src/data/sql")
file(GLOB old_module_sql "${PORTABLE_DIST_DIR}/src/modules/*/data/sql")
foreach(sql_dir IN LISTS old_module_sql)
    file(REMOVE_RECURSE "${sql_dir}")
endforeach()
file(COPY "${core}/data/sql" DESTINATION "${PORTABLE_DIST_DIR}/src/data")
file(COPY "${core}/LICENSE" DESTINATION "${PORTABLE_DIST_DIR}/licenses")
file(RENAME "${PORTABLE_DIST_DIR}/licenses/LICENSE" "${PORTABLE_DIST_DIR}/licenses/azerothcore-wotlk.txt")

foreach(app authserver worldserver)
    file(COPY "${core}/src/server/apps/${app}/${app}.conf.dist"
        DESTINATION "${PORTABLE_DIST_DIR}/configs")
endforeach()

file(READ "${PORTABLE_SOURCE_DIR}/versions.lock.json" lock)
string(JSON module_count LENGTH "${lock}" modules)
math(EXPR last_module "${module_count} - 1")
foreach(index RANGE 0 ${last_module})
    string(JSON name GET "${lock}" modules ${index} name)
    set(module "${core}/modules/${name}")
    if(NOT IS_DIRECTORY "${module}/src")
        message(FATAL_ERROR "Prepared module is missing: ${name}")
    endif()
    if(IS_DIRECTORY "${module}/data/sql")
        file(MAKE_DIRECTORY "${PORTABLE_DIST_DIR}/src/modules/${name}/data")
        file(COPY "${module}/data/sql" DESTINATION "${PORTABLE_DIST_DIR}/src/modules/${name}/data")
    endif()
    file(GLOB configs "${module}/conf/*.conf.dist")
    if(NOT configs)
        message(FATAL_ERROR "Module configuration template is missing: ${name}")
    endif()
    file(COPY ${configs} DESTINATION "${PORTABLE_DIST_DIR}/configs/modules")
    file(GLOB licenses "${module}/LICENSE*" "${module}/COPYING*")
    if(licenses)
        file(MAKE_DIRECTORY "${PORTABLE_DIST_DIR}/licenses/${name}")
        file(COPY ${licenses} DESTINATION "${PORTABLE_DIST_DIR}/licenses/${name}")
    elseif(NOT IS_DIRECTORY "${PORTABLE_SOURCE_DIR}/licenses/${name}")
        message(FATAL_ERROR "Missing upstream license notice for ${name}")
    endif()
endforeach()

string(JSON addon_count LENGTH "${lock}" clientAddons)
if(addon_count GREATER 0)
    math(EXPR last_addon "${addon_count} - 1")
    foreach(index RANGE 0 ${last_addon})
        string(JSON name GET "${lock}" clientAddons ${index} name)
        string(JSON revision GET "${lock}" clientAddons ${index} revision)
        string(JSON interface GET "${lock}" clientAddons ${index} interface)
        string(JSON toc GET "${lock}" clientAddons ${index} toc)
        string(JSON license GET "${lock}" clientAddons ${index} license)
        set(addon "${PORTABLE_SOURCE_DIR}/.module-cache/prepared-addons/${name}")
        if(NOT EXISTS "${addon}/${toc}" OR NOT EXISTS "${addon}/${license}"
            OR NOT EXISTS "${addon}/README.md" OR NOT EXISTS "${addon}/SOURCE_REVISION.txt")
            message(FATAL_ERROR "Prepared client addon is missing: ${name}. Run cmake -P cmake/PrepareModules.cmake first.")
        endif()
        file(READ "${addon}/SOURCE_REVISION.txt" exported_revision)
        string(STRIP "${exported_revision}" exported_revision)
        if(NOT exported_revision STREQUAL revision)
            message(FATAL_ERROR "Prepared client addon ${name} does not match its locked revision")
        endif()
        file(STRINGS "${addon}/${toc}" toc_lines ENCODING UTF-8)
        set(interface_matches FALSE)
        foreach(line IN LISTS toc_lines)
            string(STRIP "${line}" line)
            if(line MATCHES "^##[ \t]*Interface[ \t]*:[ \t]*${interface}[ \t]*$")
                set(interface_matches TRUE)
            endif()
            if(line STREQUAL "" OR line MATCHES "^#")
                continue()
            endif()
            string(REPLACE "\\" "/" asset "${line}")
            if(IS_ABSOLUTE "${asset}" OR asset MATCHES "(^|/)[.][.](/|$)" OR NOT EXISTS "${addon}/${asset}")
                message(FATAL_ERROR "Prepared client addon ${name} is missing TOC asset: ${asset}")
            endif()
        endforeach()
        if(NOT interface EQUAL 30300 OR NOT interface_matches)
            message(FATAL_ERROR "Prepared client addon ${name} does not target WotLK Interface 30300")
        endif()
        file(REMOVE_RECURSE "${PORTABLE_DIST_DIR}/addons/${name}")
        file(COPY "${addon}/" DESTINATION "${PORTABLE_DIST_DIR}/addons/${name}" PATTERN ".portable-source" EXCLUDE)
        file(MAKE_DIRECTORY "${PORTABLE_DIST_DIR}/licenses/${name}")
        file(COPY "${addon}/${license}" DESTINATION "${PORTABLE_DIST_DIR}/licenses/${name}")
    endforeach()
endif()

# The launcher embeds and merges these settings into complete templates at first run.
file(COPY "${PORTABLE_SOURCE_DIR}/cmd/startup/profiles/" DESTINATION "${PORTABLE_DIST_DIR}/defaults")
file(COPY "${PORTABLE_SOURCE_DIR}/licenses/" DESTINATION "${PORTABLE_DIST_DIR}/licenses")
file(COPY "${PORTABLE_SOURCE_DIR}/docs/" DESTINATION "${PORTABLE_DIST_DIR}/docs")
# Compare manifest contents rather than timestamps when assembling again.
configure_file("${PORTABLE_SOURCE_DIR}/versions.lock.json"
    "${PORTABLE_DIST_DIR}/versions.lock.json" COPYONLY)
file(COPY "${PORTABLE_SOURCE_DIR}/README.md" "${PORTABLE_SOURCE_DIR}/LICENSE"
    DESTINATION "${PORTABLE_DIST_DIR}")
file(GLOB patches "${PORTABLE_SOURCE_DIR}/patches/*.patch")
if(patches)
    file(COPY ${patches} DESTINATION "${PORTABLE_DIST_DIR}/patches")
endif()
message(STATUS "Portable distribution assembled at ${PORTABLE_DIST_DIR}")
