# Standalone client addon assets; no server build or source download is needed.
# cmake -DPACKAGE_VERSION=1.0.0 -P cmake/PackageClientAddons.cmake
cmake_minimum_required(VERSION 3.19)

if(NOT PORTABLE_SOURCE_DIR)
    get_filename_component(PORTABLE_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
get_filename_component(PORTABLE_SOURCE_DIR "${PORTABLE_SOURCE_DIR}" ABSOLUTE)
if(NOT PACKAGE_OUTPUT_DIR)
    set(PACKAGE_OUTPUT_DIR "${PORTABLE_SOURCE_DIR}/output")
endif()
get_filename_component(PACKAGE_OUTPUT_DIR "${PACKAGE_OUTPUT_DIR}" ABSOLUTE)
if(NOT DEFINED PACKAGE_VERSION)
    if(DEFINED ENV{PACKAGE_VERSION})
        set(PACKAGE_VERSION "$ENV{PACKAGE_VERSION}")
    else()
        set(PACKAGE_VERSION "dev")
    endif()
endif()
if(NOT PACKAGE_VERSION MATCHES "^[A-Za-z0-9][A-Za-z0-9._-]*$")
    message(FATAL_ERROR "PACKAGE_VERSION must be a nonempty, filename-safe version")
endif()

file(READ "${PORTABLE_SOURCE_DIR}/versions.lock.json" lock)
string(JSON schema GET "${lock}" schemaVersion)
if(NOT schema EQUAL 1)
    message(FATAL_ERROR "Unsupported versions.lock.json schema: ${schema}")
endif()
set(staging_root "${PORTABLE_SOURCE_DIR}/.module-cache/package-addons")
file(MAKE_DIRECTORY "${staging_root}" "${PACKAGE_OUTPUT_DIR}")
file(LOCK "${staging_root}/package.lock" GUARD PROCESS TIMEOUT 60)
set(archive_names)
set(addon_names)
string(JSON addon_count LENGTH "${lock}" clientAddons)
if(addon_count EQUAL 0)
    message(STATUS "No client addons to package")
    return()
endif()
find_package(Git REQUIRED)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
file(SHA256 "${PORTABLE_SOURCE_DIR}/cmake/PrepareModules.cmake" prepare_script_hash)
math(EXPR last_addon "${addon_count} - 1")
foreach(index RANGE 0 ${last_addon})
    string(JSON name GET "${lock}" clientAddons ${index} name)
    string(JSON archive_name ERROR_VARIABLE archive_name_error GET "${lock}" clientAddons ${index} archiveName)
    if(archive_name_error)
        set(archive_name "${name}")
    endif()
    string(JSON url GET "${lock}" clientAddons ${index} url)
    string(JSON revision GET "${lock}" clientAddons ${index} revision)
    string(JSON interface GET "${lock}" clientAddons ${index} interface)
    string(JSON toc GET "${lock}" clientAddons ${index} toc)
    string(JSON license GET "${lock}" clientAddons ${index} license)
    string(JSON source_module ERROR_VARIABLE source_module_error GET "${lock}" clientAddons ${index} sourceModule)
    set(module_patches)
    string(LENGTH "${revision}" revision_length)
    if(NOT name MATCHES "^[A-Za-z0-9_-]+$"
        OR NOT archive_name MATCHES "^[A-Za-z0-9][A-Za-z0-9._-]*$"
        OR NOT toc STREQUAL "${name}.toc"
        OR NOT license MATCHES "^[A-Za-z0-9][A-Za-z0-9._-]*$"
        OR NOT url MATCHES "^https://github.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+[.]git$"
        OR NOT revision MATCHES "^[a-f0-9]+$" OR NOT revision_length EQUAL 40
        OR NOT interface EQUAL 30300)
        message(FATAL_ERROR "Invalid pinned WotLK client addon: ${name}")
    endif()
    string(TOLOWER "${archive_name}" archive_key)
    string(TOLOWER "${name}" addon_key)
    if(archive_key IN_LIST archive_names OR addon_key IN_LIST addon_names)
        message(FATAL_ERROR "Duplicate client addon name or archiveName: ${name}")
    endif()
    list(APPEND archive_names "${archive_key}")
    list(APPEND addon_names "${addon_key}")

    set(source "${PORTABLE_SOURCE_DIR}/.module-cache/prepared-addons/${name}")
    if(NOT EXISTS "${source}/.portable-source" OR IS_DIRECTORY "${source}/.portable-source"
        OR IS_SYMLINK "${source}/.portable-source")
        message(FATAL_ERROR "Prepared client addon is missing: ${name}. Run cmake -P cmake/PrepareModules.cmake first.")
    endif()
    set(expected_stamp "prepare: ${prepare_script_hash}\n${url}\n${revision}\ninterface: ${interface}\n")
    if(NOT source_module_error)
        string(JSON source_path GET "${lock}" clientAddons ${index} sourcePath)
        if(NOT source_module MATCHES "^mod-[a-z0-9-]+$" OR IS_ABSOLUTE "${source_path}"
            OR NOT source_path MATCHES "^[A-Za-z0-9_/-]+$" OR source_path MATCHES "(^|/)[.][.]?(/|$)|//")
            message(FATAL_ERROR "Invalid module-sourced client addon: ${name}")
        endif()
        set(module_found FALSE)
        string(JSON module_count LENGTH "${lock}" modules)
        math(EXPR last_module "${module_count} - 1")
        foreach(module_index RANGE 0 ${last_module})
            string(JSON module_name GET "${lock}" modules ${module_index} name)
            if(NOT module_name STREQUAL source_module)
                continue()
            endif()
            string(JSON module_url GET "${lock}" modules ${module_index} url)
            string(JSON module_revision GET "${lock}" modules ${module_index} revision)
            if(NOT module_url STREQUAL url OR NOT module_revision STREQUAL revision)
                message(FATAL_ERROR "Client addon ${name} differs from its locked source module")
            endif()
            string(JSON core_source GET "${lock}" core source)
            set(module_stamp "prepare: ${prepare_script_hash}\n${url}\n${revision}\n")
            string(JSON patch_count ERROR_VARIABLE patch_error LENGTH "${lock}" modules ${module_index} patches)
            if(NOT patch_error AND patch_count GREATER 0)
                math(EXPR last_patch "${patch_count} - 1")
                foreach(patch_index RANGE 0 ${last_patch})
                    string(JSON patch GET "${lock}" modules ${module_index} patches ${patch_index})
                    if(IS_ABSOLUTE "${patch}" OR patch MATCHES "(^|/)[.][.]?(/|$)|:|\\\\" OR NOT EXISTS "${PORTABLE_SOURCE_DIR}/${patch}")
                        message(FATAL_ERROR "Invalid source module patch: ${patch}")
                    endif()
                    file(SHA256 "${PORTABLE_SOURCE_DIR}/${patch}" patch_hash)
                    string(APPEND module_stamp "${patch}: ${patch_hash}\n")
                    list(APPEND module_patches "${PORTABLE_SOURCE_DIR}/${patch}")
                endforeach()
            endif()
            string(APPEND expected_stamp "module: ${source_module}\npath: ${source_path}\n${module_stamp}")
            set(module_found TRUE)
        endforeach()
        if(NOT module_found)
            message(FATAL_ERROR "Client addon ${name} has no locked source module")
        endif()
    endif()
    file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/ExportClientAddon.py" addon_export_hash)
    string(APPEND expected_stamp "export: ${addon_export_hash}\n")
    set(addon_patches)
    string(JSON addon_patch_count ERROR_VARIABLE addon_patch_error LENGTH "${lock}" clientAddons ${index} patches)
    if(NOT addon_patch_error AND addon_patch_count GREATER 0)
        math(EXPR last_addon_patch "${addon_patch_count} - 1")
        foreach(patch_index RANGE 0 ${last_addon_patch})
            string(JSON patch GET "${lock}" clientAddons ${index} patches ${patch_index})
            set(patch_file "${PORTABLE_SOURCE_DIR}/${patch}")
            if(NOT patch MATCHES "^patches/[A-Za-z0-9_.-]+[.]patch$"
                OR NOT EXISTS "${patch_file}" OR IS_DIRECTORY "${patch_file}" OR IS_SYMLINK "${patch_file}")
                message(FATAL_ERROR "Missing or invalid client addon patch: ${patch}")
            endif()
            file(SHA256 "${patch_file}" patch_hash)
            string(APPEND expected_stamp "${patch}: ${patch_hash}\n")
            list(APPEND addon_patches "${patch_file}")
        endforeach()
    endif()
    file(READ "${source}/.portable-source" prepared_stamp)
    if(NOT prepared_stamp STREQUAL expected_stamp)
        message(FATAL_ERROR "Prepared client addon ${name} has a stale or invalid preparation stamp. Run cmake -P cmake/PrepareModules.cmake first.")
    endif()
    set(required_files "${toc}" "${license}" README.md SOURCE_REVISION.txt)
    if(addon_patches)
        list(APPEND required_files SOURCE_MANIFEST.json)
    endif()
    foreach(required IN LISTS required_files)
        if(NOT EXISTS "${source}/${required}" OR IS_DIRECTORY "${source}/${required}")
            message(FATAL_ERROR "Prepared client addon ${name} is missing ${required}")
        endif()
        file(SIZE "${source}/${required}" required_size)
        if(required_size EQUAL 0)
            message(FATAL_ERROR "Prepared client addon ${name} has an empty ${required}")
        endif()
    endforeach()
    file(READ "${source}/SOURCE_REVISION.txt" source_revision)
    string(STRIP "${source_revision}" source_revision)
    if(NOT source_revision STREQUAL revision)
        message(FATAL_ERROR "Prepared client addon ${name} differs from its locked source revision")
    endif()
    file(STRINGS "${source}/${toc}" toc_lines ENCODING UTF-8)
    set(interface_count 0)
    foreach(line IN LISTS toc_lines)
        string(STRIP "${line}" line)
        if(line MATCHES "^##[ \t]*Interface[ \t]*:[ \t]*([0-9]+)[ \t]*$")
            if(NOT CMAKE_MATCH_1 STREQUAL "${interface}")
                message(FATAL_ERROR "Client addon ${name} must declare WotLK Interface ${interface}")
            endif()
            math(EXPR interface_count "${interface_count} + 1")
        endif()
        if(line STREQUAL "" OR line MATCHES "^#")
            continue()
        endif()
        string(REPLACE "\\" "/" asset "${line}")
        if(IS_ABSOLUTE "${asset}" OR asset MATCHES "(^|/)[.][.]?(/|$)|:|(^|/)([.]git|[.]github|[.]portable-source)(/|$)"
            OR NOT EXISTS "${source}/${asset}" OR IS_DIRECTORY "${source}/${asset}")
            message(FATAL_ERROR "Client addon ${name} has a missing or invalid TOC asset: ${asset}")
        endif()
    endforeach()
    if(NOT interface_count EQUAL 1)
        message(FATAL_ERROR "Client addon ${name} must declare WotLK Interface ${interface} exactly once")
    endif()

    # Export the pinned cached commit independently of the mutable prepared files.
    # Packaging never fetches sources or invokes server/module preparation.
    set(cached_source "${PORTABLE_SOURCE_DIR}/.module-cache/client-addon-${name}")
    if(NOT source_module_error)
        set(cached_source "${PORTABLE_SOURCE_DIR}/.module-cache/${source_module}")
    endif()
    if(NOT EXISTS "${cached_source}/.git")
        message(FATAL_ERROR "Cached client addon repository is missing: ${name}. Run cmake -P cmake/PrepareModules.cmake first.")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${cached_source}" cat-file -e "${revision}^{commit}"
        RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cached client addon ${name} is missing pinned commit ${revision}. Run cmake -P cmake/PrepareModules.cmake first.")
    endif()
    set(stage "${staging_root}/${name}")
    set(export "${stage}/${name}")
    set(raw_export "${export}")
    if(NOT source_module_error)
        set(raw_export "${stage}/module-source")
    endif()
    set(source_archive "${stage}/source.tar")
    file(REMOVE_RECURSE "${stage}")
    file(MAKE_DIRECTORY "${export}" "${raw_export}")
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${cached_source}" archive --format=tar
        "--output=${source_archive}" "${revision}"
        RESULT_VARIABLE result ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot export pinned client addon ${name}: ${error}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xf "${source_archive}"
        WORKING_DIRECTORY "${raw_export}" RESULT_VARIABLE result ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot extract pinned client addon ${name}: ${error}")
    endif()
    file(REMOVE "${source_archive}")
    if(NOT source_module_error)
        foreach(module_patch IN LISTS module_patches)
            file(READ "${module_patch}" patch_contents)
            string(REPLACE "\r\n" "\n" patch_contents "${patch_contents}")
            string(REGEX REPLACE "\n$" "" patch_contents "${patch_contents}")
            file(CONFIGURE OUTPUT "${stage}/source.patch" CONTENT "@patch_contents@" @ONLY NEWLINE_STYLE LF)
            execute_process(COMMAND "${CMAKE_COMMAND}" -E env "GIT_CEILING_DIRECTORIES=${staging_root}"
                "${GIT_EXECUTABLE}" -C "${raw_export}" apply "${stage}/source.patch"
                RESULT_VARIABLE result ERROR_VARIABLE error)
            if(NOT result EQUAL 0)
                message(FATAL_ERROR "Cannot apply addon source module patch ${module_patch}: ${error}")
            endif()
        endforeach()
        if(NOT IS_DIRECTORY "${raw_export}/${source_path}")
            message(FATAL_ERROR "Client addon ${name} source path is missing from its locked module")
        endif()
        file(COPY "${raw_export}/${source_path}/" DESTINATION "${export}")
        file(COPY "${raw_export}/${license}" "${raw_export}/README.md" DESTINATION "${export}")
        file(REMOVE_RECURSE "${raw_export}")
        file(REMOVE "${stage}/source.patch")
    endif()
    foreach(addon_patch IN LISTS addon_patches)
        file(READ "${addon_patch}" patch_contents)
        string(REPLACE "\r\n" "\n" patch_contents "${patch_contents}")
        string(REGEX REPLACE "\n$" "" patch_contents "${patch_contents}")
        file(CONFIGURE OUTPUT "${stage}/addon.patch" CONTENT "@patch_contents@" @ONLY NEWLINE_STYLE LF)
        foreach(operation "--numstat" "--check" "" "--reverse;--check")
            execute_process(COMMAND "${CMAKE_COMMAND}" -E env "GIT_CEILING_DIRECTORIES=${staging_root}"
                "${GIT_EXECUTABLE}" -C "${export}" apply ${operation} "${stage}/addon.patch"
                RESULT_VARIABLE result OUTPUT_VARIABLE patch_output ERROR_VARIABLE error)
            if(NOT result EQUAL 0 OR (operation STREQUAL "--numstat" AND patch_output STREQUAL ""))
                message(FATAL_ERROR "Cannot apply locked client addon patch ${addon_patch}: ${error}")
            endif()
        endforeach()
    endforeach()
    file(REMOVE "${stage}/addon.patch")
    file(REMOVE_RECURSE "${export}/.github")
    file(REMOVE "${export}/.gitignore" "${export}/.coderabbit.yaml" "${export}/AGENTS.md")
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_LIST_DIR}/ExportClientAddon.py"
        --repository "${PORTABLE_SOURCE_DIR}" --addon "${name}"
        --destination "${export}" --manifest-only RESULT_VARIABLE result ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot record client addon source provenance: ${error}")
    endif()

    # Verify every asset, including textures and files not listed in the TOC.
    file(GLOB_RECURSE source_paths LIST_DIRECTORIES TRUE RELATIVE "${source}" "${source}/*")
    set(source_files)
    foreach(path IN LISTS source_paths)
        if(path STREQUAL ".portable-source")
            continue()
        endif()
        if(IS_SYMLINK "${source}/${path}")
            message(FATAL_ERROR "Client addon ${name} contains a symbolic link: ${path}")
        endif()
        if(NOT IS_DIRECTORY "${source}/${path}")
            list(APPEND source_files "${path}")
        endif()
    endforeach()
    file(GLOB_RECURSE expected_files LIST_DIRECTORIES FALSE RELATIVE "${export}" "${export}/*")
    list(SORT source_files)
    list(SORT expected_files)
    if(NOT source_files STREQUAL expected_files)
        message(FATAL_ERROR "Prepared client addon ${name} has missing or extra assets compared with pinned commit ${revision}. Run cmake -P cmake/PrepareModules.cmake first.")
    endif()
    foreach(path IN LISTS expected_files)
        file(SHA256 "${source}/${path}" source_hash)
        file(SHA256 "${export}/${path}" expected_hash)
        if(NOT source_hash STREQUAL expected_hash)
            message(FATAL_ERROR "Prepared client addon ${name} has a corrupt asset: ${path}. Run cmake -P cmake/PrepareModules.cmake first.")
        endif()
    endforeach()
    # Export runtime assets from the fully verified pinned tree. Prepared sources
    # stay intact for tests; unknown and dynamically loaded resources are kept.
    set(runtime_stage "${stage}/runtime")
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_LIST_DIR}/AddonRuntime.py"
        --source "${export}" --toc "${toc}" --destination "${runtime_stage}/${name}"
        RESULT_VARIABLE result ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot export client addon runtime ${name}: ${error}")
    endif()
    set(zip "${PACKAGE_OUTPUT_DIR}/${archive_name}-${PACKAGE_VERSION}.zip")
    set(temporary_zip "${zip}.tmp")
    file(REMOVE "${temporary_zip}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${temporary_zip}" --format=zip -- "${name}"
        WORKING_DIRECTORY "${runtime_stage}" RESULT_VARIABLE result ERROR_VARIABLE error)
    file(REMOVE_RECURSE "${stage}")
    if(NOT result EQUAL 0)
        file(REMOVE "${temporary_zip}")
        message(FATAL_ERROR "Cannot package client addon ${name}: ${error}")
    endif()
    file(RENAME "${temporary_zip}" "${zip}")
    message(STATUS "Packaged standalone client addon: ${zip} (install folder: ${name})")
endforeach()
