# Standalone client addon assets; no server build or source download is needed.
# cmake -DPACKAGE_VERSION=1.0.0 -P cmake/PackageClientAddons.cmake
cmake_minimum_required(VERSION 3.19)

if(NOT PORTABLE_SOURCE_DIR)
    get_filename_component(PORTABLE_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
get_filename_component(PORTABLE_SOURCE_DIR "${PORTABLE_SOURCE_DIR}" ABSOLUTE)
if(NOT PACKAGE_OUTPUT_DIR)
    set(PACKAGE_OUTPUT_DIR "${PORTABLE_SOURCE_DIR}/output")
endif()
get_filename_component(PACKAGE_OUTPUT_DIR "${PACKAGE_OUTPUT_DIR}" ABSOLUTE)
if(NOT DEFINED PACKAGE_VERSION)
    if(DEFINED ENV{PACKAGE_VERSION})
        set(PACKAGE_VERSION "$ENV{PACKAGE_VERSION}")
    else()
        set(PACKAGE_VERSION "dev")
    endif()
endif()
if(NOT PACKAGE_VERSION MATCHES "^[A-Za-z0-9][A-Za-z0-9._-]*$")
    message(FATAL_ERROR "PACKAGE_VERSION must be a nonempty, filename-safe version")
endif()

file(READ "${PORTABLE_SOURCE_DIR}/versions.lock.json" lock)
string(JSON schema GET "${lock}" schemaVersion)
if(NOT schema EQUAL 1)
    message(FATAL_ERROR "Unsupported versions.lock.json schema: ${schema}")
endif()
set(staging_root "${PORTABLE_SOURCE_DIR}/.module-cache/package-addons")
file(MAKE_DIRECTORY "${staging_root}" "${PACKAGE_OUTPUT_DIR}")
file(LOCK "${staging_root}/package.lock" GUARD PROCESS TIMEOUT 60)
set(archive_names)
set(addon_names)
string(JSON addon_count LENGTH "${lock}" clientAddons)
if(addon_count EQUAL 0)
    message(STATUS "No client addons to package")
    return()
endif()
find_package(Git REQUIRED)
file(SHA256 "${PORTABLE_SOURCE_DIR}/cmake/PrepareModules.cmake" prepare_script_hash)
math(EXPR last_addon "${addon_count} - 1")
foreach(index RANGE 0 ${last_addon})
    string(JSON name GET "${lock}" clientAddons ${index} name)
    string(JSON archive_name ERROR_VARIABLE archive_name_error GET "${lock}" clientAddons ${index} archiveName)
    if(archive_name_error)
        set(archive_name "${name}")
    endif()
    string(JSON url GET "${lock}" clientAddons ${index} url)
    string(JSON revision GET "${lock}" clientAddons ${index} revision)
    string(JSON interface GET "${lock}" clientAddons ${index} interface)
    string(JSON toc GET "${lock}" clientAddons ${index} toc)
    string(JSON license GET "${lock}" clientAddons ${index} license)
    string(LENGTH "${revision}" revision_length)
    if(NOT name MATCHES "^[A-Za-z0-9_-]+$"
        OR NOT archive_name MATCHES "^[A-Za-z0-9][A-Za-z0-9._-]*$"
        OR NOT toc STREQUAL "${name}.toc"
        OR NOT license MATCHES "^[A-Za-z0-9][A-Za-z0-9._-]*$"
        OR NOT url MATCHES "^https://github.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+[.]git$"
        OR NOT revision MATCHES "^[a-f0-9]+$" OR NOT revision_length EQUAL 40
        OR NOT interface EQUAL 30300)
        message(FATAL_ERROR "Invalid pinned WotLK client addon: ${name}")
    endif()
    string(TOLOWER "${archive_name}" archive_key)
    string(TOLOWER "${name}" addon_key)
    if(archive_key IN_LIST archive_names OR addon_key IN_LIST addon_names)
        message(FATAL_ERROR "Duplicate client addon name or archiveName: ${name}")
    endif()
    list(APPEND archive_names "${archive_key}")
    list(APPEND addon_names "${addon_key}")

    set(source "${PORTABLE_SOURCE_DIR}/.module-cache/prepared-addons/${name}")
    if(NOT EXISTS "${source}/.portable-source" OR IS_DIRECTORY "${source}/.portable-source"
        OR IS_SYMLINK "${source}/.portable-source")
        message(FATAL_ERROR "Prepared client addon is missing: ${name}. Run cmake -P cmake/PrepareModules.cmake first.")
    endif()
    set(expected_stamp "prepare: ${prepare_script_hash}\n${url}\n${revision}\ninterface: ${interface}\n")
    file(READ "${source}/.portable-source" prepared_stamp)
    if(NOT prepared_stamp STREQUAL expected_stamp)
        message(FATAL_ERROR "Prepared client addon ${name} has a stale or invalid preparation stamp. Run cmake -P cmake/PrepareModules.cmake first.")
    endif()
    foreach(required "${toc}" "${license}" README.md SOURCE_REVISION.txt)
        if(NOT EXISTS "${source}/${required}" OR IS_DIRECTORY "${source}/${required}")
            message(FATAL_ERROR "Prepared client addon ${name} is missing ${required}")
        endif()
        file(SIZE "${source}/${required}" required_size)
        if(required_size EQUAL 0)
            message(FATAL_ERROR "Prepared client addon ${name} has an empty ${required}")
        endif()
    endforeach()
    file(READ "${source}/SOURCE_REVISION.txt" source_revision)
    string(STRIP "${source_revision}" source_revision)
    if(NOT source_revision STREQUAL revision)
        message(FATAL_ERROR "Prepared client addon ${name} differs from its locked source revision")
    endif()
    file(STRINGS "${source}/${toc}" toc_lines ENCODING UTF-8)
    set(interface_count 0)
    foreach(line IN LISTS toc_lines)
        string(STRIP "${line}" line)
        if(line MATCHES "^##[ \t]*Interface[ \t]*:[ \t]*([0-9]+)[ \t]*$")
            if(NOT CMAKE_MATCH_1 STREQUAL "${interface}")
                message(FATAL_ERROR "Client addon ${name} must declare WotLK Interface ${interface}")
            endif()
            math(EXPR interface_count "${interface_count} + 1")
        endif()
        if(line STREQUAL "" OR line MATCHES "^#")
            continue()
        endif()
        string(REPLACE "\\" "/" asset "${line}")
        if(IS_ABSOLUTE "${asset}" OR asset MATCHES "(^|/)[.][.]?(/|$)|:|(^|/)([.]git|[.]github|[.]portable-source)(/|$)"
            OR NOT EXISTS "${source}/${asset}" OR IS_DIRECTORY "${source}/${asset}")
            message(FATAL_ERROR "Client addon ${name} has a missing or invalid TOC asset: ${asset}")
        endif()
    endforeach()
    if(NOT interface_count EQUAL 1)
        message(FATAL_ERROR "Client addon ${name} must declare WotLK Interface ${interface} exactly once")
    endif()

    # Export the pinned cached commit independently of the mutable prepared files.
    # Packaging never fetches sources or invokes server/module preparation.
    set(cached_source "${PORTABLE_SOURCE_DIR}/.module-cache/client-addon-${name}")
    if(NOT EXISTS "${cached_source}/.git")
        message(FATAL_ERROR "Cached client addon repository is missing: ${name}. Run cmake -P cmake/PrepareModules.cmake first.")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${cached_source}" cat-file -e "${revision}^{commit}"
        RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cached client addon ${name} is missing pinned commit ${revision}. Run cmake -P cmake/PrepareModules.cmake first.")
    endif()
    set(stage "${staging_root}/${name}")
    set(export "${stage}/${name}")
    set(source_archive "${stage}/source.tar")
    file(REMOVE_RECURSE "${stage}")
    file(MAKE_DIRECTORY "${export}")
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${cached_source}" archive --format=tar
        "--output=${source_archive}" "${revision}"
        RESULT_VARIABLE result ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot export pinned client addon ${name}: ${error}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xf "${source_archive}"
        WORKING_DIRECTORY "${export}" RESULT_VARIABLE result ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot extract pinned client addon ${name}: ${error}")
    endif()
    file(REMOVE "${source_archive}")
    file(REMOVE_RECURSE "${export}/.github")
    file(REMOVE "${export}/.gitignore" "${export}/.coderabbit.yaml" "${export}/AGENTS.md")
    file(WRITE "${export}/SOURCE_REVISION.txt" "${revision}\n")

    # Verify every asset, including textures and files not listed in the TOC.
    file(GLOB_RECURSE source_paths LIST_DIRECTORIES TRUE RELATIVE "${source}" "${source}/*")
    set(source_files)
    foreach(path IN LISTS source_paths)
        if(path STREQUAL ".portable-source")
            continue()
        endif()
        if(IS_SYMLINK "${source}/${path}")
            message(FATAL_ERROR "Client addon ${name} contains a symbolic link: ${path}")
        endif()
        if(NOT IS_DIRECTORY "${source}/${path}")
            list(APPEND source_files "${path}")
        endif()
    endforeach()
    file(GLOB_RECURSE expected_files LIST_DIRECTORIES FALSE RELATIVE "${export}" "${export}/*")
    list(SORT source_files)
    list(SORT expected_files)
    if(NOT source_files STREQUAL expected_files)
        message(FATAL_ERROR "Prepared client addon ${name} has missing or extra assets compared with pinned commit ${revision}. Run cmake -P cmake/PrepareModules.cmake first.")
    endif()
    foreach(path IN LISTS expected_files)
        file(SHA256 "${source}/${path}" source_hash)
        file(SHA256 "${export}/${path}" expected_hash)
        if(NOT source_hash STREQUAL expected_hash)
            message(FATAL_ERROR "Prepared client addon ${name} has a corrupt asset: ${path}. Run cmake -P cmake/PrepareModules.cmake first.")
        endif()
    endforeach()
    set(zip "${PACKAGE_OUTPUT_DIR}/${archive_name}-${PACKAGE_VERSION}.zip")
    set(temporary_zip "${zip}.tmp")
    file(REMOVE "${temporary_zip}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${temporary_zip}" --format=zip -- "${name}"
        WORKING_DIRECTORY "${stage}" RESULT_VARIABLE result ERROR_VARIABLE error)
    file(REMOVE_RECURSE "${stage}")
    if(NOT result EQUAL 0)
        file(REMOVE "${temporary_zip}")
        message(FATAL_ERROR "Cannot package client addon ${name}: ${error}")
    endif()
    file(RENAME "${temporary_zip}" "${zip}")
    message(STATUS "Packaged standalone client addon: ${zip} (install folder: ${name})")
endforeach()
